name: PowerPC

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.c"
      - ".github/workflows/ppc64.yml"
  pull_request:

jobs:
  powerpc:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Ubuntu PowerPC

    steps:
      - uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Run commands
        id: runcmd
        with:
          arch: ppc64le
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install -q -y cmake gcc

          run: |
            cmake -B build
            cmake --build build
            ctest --test-dir build --preset default -V
